# application-test.yml  (NEU)
logging:
  level:
    root: INFO
    at.ac.tuwien.sepr.assignment.individual: DEBUG
    com.zaxxer.hikari: ERROR
  file:
    name: ./logs/wendys-family-tree.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/wendys-family-tree-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 14
      total-size-cap: 200MB
      clean-history-on-start: true
  pattern:
    # Hinweis: der 'level'-Eintrag ist unüblich, aber unschädlich; wichtig sind console/file:
    level: "r=%X{r} ip=%X{ip} %5p"
    console: "%d{ISO8601} r=%X{r} ip=%X{ip} %-5level %pid --- [%property{spring.application.name}] [%thread] %logger : %msg%n"
    file:    "%d{ISO8601} r=%X{r} ip=%X{ip} %-5level %pid --- [%property{spring.application.name}] [%thread] %logger : %msg%n"

spring:
  application:
    name: wendys-family-tree
  datasource:
    url: jdbc:h2:mem:wendydb-test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/createSchema.sql
      data-locations: classpath:sql/insertData.sql

server:
  port: 8080
  error:
    include-message: always

app:
  storage:
    horseImageDir: ./data/horse-images
