logging:
  level:
    root: INFO
    at.ac.tuwien.sepr.assignment.individual: DEBUG
    com.zaxxer.hikari: ERROR
  file:
    name: ./logs/wendys-family-tree.log      # aktuelles Log (ohne Datum)
  logback:
    rollingpolicy:
      # tägliche Rotation + Größen-Rollover; Spring Boot nutzt SizeAndTimeBasedRollingPolicy bei %d und %i
      file-name-pattern: ./logs/wendys-family-tree-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 14
      total-size-cap: 200MB
      clean-history-on-start: true
  pattern:
    level: "r=%X{r} ip=%X{ip} %5p"
    console: "%d{ISO8601} r=%X{r} ip=%X{ip} %-5level %pid --- [%property{spring.application.name}] [%thread] %logger : %msg%n"
    file:    "%d{ISO8601} r=%X{r} ip=%X{ip} %-5level %pid --- [%property{spring.application.name}] [%thread] %logger : %msg%n"

spring:
  application:
    name: wendys-family-tree
  datasource:
    url: "jdbc:h2:./wendydb;AUTO_SERVER=TRUE;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

server:
  port: 8080
  error:
    include-message: always

app:
  storage:
    horseImageDir: ./data/horse-images
